{"name": "test_case2[3-4-5]", "status": "failed", "statusDetails": {"message": "AssertionError: assert '4' == '5'\n  - 4\n  + 5", "trace": "testid = '3', postdata = '4', exceptval = '5'\n\n    @pytest.mark.parametrize('testid,postdata,exceptval',testdata)\n    def test_case2(testid,postdata,exceptval):\n        log.info(f'开始进行测试：测试编号为{testid}')\n        try:\n            assert postdata == exceptval\n        except AssertionError as e:\n            log.error(f'测试失败: 失败信息如下: {e}')\n>           raise e\n\nmain.py:15: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\ntestid = '3', postdata = '4', exceptval = '5'\n\n    @pytest.mark.parametrize('testid,postdata,exceptval',testdata)\n    def test_case2(testid,postdata,exceptval):\n        log.info(f'开始进行测试：测试编号为{testid}')\n        try:\n>           assert postdata == exceptval\nE           AssertionError: assert '4' == '5'\nE             - 4\nE             + 5\n\nmain.py:12: AssertionError"}, "attachments": [{"name": "log", "source": "336e190b-af22-4a38-ace6-829814b79940-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "testid", "value": "'3'"}, {"name": "postdata", "value": "'4'"}, {"name": "exceptval", "value": "'5'"}], "start": 1584025916121, "stop": 1584025916123, "uuid": "ff6b62e6-9bab-4c8e-93ff-3c1ceeaf218c", "historyId": "17f362042b3e8d2dbd45b9df0f0fa6b3", "testCaseId": "3390f6e6e175ad3d5eb0a254959256fd", "fullName": "main#test_case2", "labels": [{"name": "suite", "value": "main"}, {"name": "host", "value": "zzy"}, {"name": "thread", "value": "5469-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "main"}]}